import os

from fuzzywuzzy import fuzz
from utils import File

from lk_admin_regions import GNDListFinalXLSX, LKAAdminBoundariesXLSX
from lk_admin_regions.corrections.ID_CORRECTION_MAP_dsd import (
    ID_CORRECTION_MAP_dsd,
)
from lk_admin_regions.corrections.ID_CORRECTION_MAP_gnd import (
    ID_CORRECTION_MAP_gnd,
)

ID_CORRECTION_MAP = ID_CORRECTION_MAP_dsd | ID_CORRECTION_MAP_gnd


def correct(d_list, dcs_region_key, hum_region_key):

    corrected_d_list = []
    for d in d_list:
        region_id = "LK-" + d[hum_region_key][2:]
        for before, after in ID_CORRECTION_MAP.items():
            if before in region_id:
                region_id = region_id.replace(before, after)
        d[dcs_region_key] = region_id
        corrected_d_list.append(d)
    return corrected_d_list


def compare(dcs_region_label, hum_admin_level):
    var_name = f"ID_CORRECTION_MAP_{dcs_region_label}"
    lines = [
        "# ⚠️ Auto Generated by workflows/temp_analyze.py. REVIEW MANUALLY.",
        "# flake8: noqa: E501",
        "",
        "",
        f"{var_name} = {{",
    ]
    print("-" * 32)
    print("LEVEL ", hum_admin_level, dcs_region_label)
    print("-" * 32)

    dcs_region_id_key = f"{dcs_region_label}_id"
    dcs_region_name_key = f"{dcs_region_label}_name"
    hum_sheet_name = f"lka_admin{hum_admin_level}"
    hum_region_id_key = f"adm{hum_admin_level}_pcode"
    hum_region_name_key = f"adm{hum_admin_level}_name"
    data_dcs = GNDListFinalXLSX.get_data_list()
    data_hum = LKAAdminBoundariesXLSX.get_sheet_name_to_d_list()

    region_id_to_name_dcs = {
        d[dcs_region_id_key]: d[dcs_region_name_key] for d in data_dcs
    }

    data_hum_corrected = correct(
        data_hum[hum_sheet_name], dcs_region_id_key, hum_region_id_key
    )
    if len(data_hum_corrected) != len(data_hum[hum_sheet_name]):
        print(
            "❌ HUM DUPLICATE IDS",
            len(data_hum_corrected),
            len(data_hum[hum_sheet_name]),
        )
    region_id_to_name_hum = {
        d[dcs_region_id_key]: d[hum_region_name_key]
        for d in data_hum_corrected
    }

    print(len(region_id_to_name_dcs), next(iter(region_id_to_name_dcs.keys())))
    print(len(region_id_to_name_hum), next(iter(region_id_to_name_hum.keys())))

    dcs_region_ids = set(region_id_to_name_dcs.keys())
    hum_region_ids = set(region_id_to_name_hum.keys())

    dcs_minus_hum = set(dcs_region_ids - hum_region_ids)
    hum_minus_dcs = set(hum_region_ids - dcs_region_ids)

    print("len(dcs_minus_hum)=", len(dcs_minus_hum))
    if dcs_minus_hum:
        for region_id in list(sorted(dcs_minus_hum))[:10]:
            print(
                "\t- ",
                region_id,
                region_id_to_name_dcs[region_id],
            )
        print("...")

    print("len(hum_minus_dcs)=", len(hum_minus_dcs))
    if hum_minus_dcs:
        for region_id in list(sorted(hum_minus_dcs))[:10]:
            print(
                "\t- ",
                region_id,
                region_id_to_name_hum[region_id],
            )
        print("...")

    lines.extend(
        [
            "    #",
            "    # " + "=" * 64,
            "    # MATCH 1 - Similar Name",
            "    # " + "=" * 64,
            "    #",
        ]
    )
    # MATCH 1 = Check if there is a DCS region
    # a) without a HUM match,
    # b) with the same or similar name,
    # c) belonging to the same parent region.
    previous_parent_region_id = None
    n_match_1 = 0
    hum_minus_dcs = set(sorted(hum_minus_dcs))
    for hum_id in hum_minus_dcs:
        hum_name = region_id_to_name_hum[hum_id]
        match_list = []

        # 1.a
        for dcs_id in dcs_minus_hum:
            parent_region_id = dcs_id[:-3]
            # 1.b
            if parent_region_id not in hum_id:
                continue
            # 1.c
            dcs_name = region_id_to_name_dcs[dcs_id]
            match_score = fuzz.ratio(dcs_name, str(hum_name))
            if match_score < 80:
                continue
            match_list.append((dcs_id, dcs_name, match_score))

        match_list.sort(key=lambda x: x[2], reverse=True)
        n_matches = len(match_list)
        if n_matches:
            print("\t", hum_id, hum_name)
            for dcs_id, dcs_name, match_score in match_list:
                parent_region_id = dcs_id[:-3]
                print("\t\t- ", dcs_id, dcs_name, match_score)
                if parent_region_id != previous_parent_region_id:
                    lines.append("    " + "# --------")
                    lines.append("    " + f"# {parent_region_id}")
                    lines.append("    " + "# --------")
                    previous_parent_region_id = parent_region_id
                n_match_1 += 1
                lines.append(
                    "    "
                    + f'"{hum_id}": "{dcs_id}",'
                    + f"  # {n_match_1:03d}."
                    + f" {hum_name} -> {dcs_name} ({match_score})"
                )
                break

    # MATCH 2 - Check if some parent has exactly one DCS Gnd without a match,
    # and exaclty one HUM Gnd without a match

    if not n_match_1:
        n_match_2 = 0
        lines.extend(
            [
                "    #",
                "    # " + "=" * 64,
                "    # MATCH 2 - Parent with same num of unmatched HUM & DCS",
                "    # " + "=" * 64,
                "    #",
            ]
        )
        parent_id_to_hum_ids = {}
        for hum_id in hum_minus_dcs:
            parent_region_id = hum_id[:-3]
            if parent_region_id not in parent_id_to_hum_ids:
                parent_id_to_hum_ids[parent_region_id] = []
            parent_id_to_hum_ids[parent_region_id].append(hum_id)
        parent_id_to_dcs_ids = {}
        for dcs_id in dcs_minus_hum:
            parent_region_id = dcs_id[:-3]
            if parent_region_id not in parent_id_to_dcs_ids:
                parent_id_to_dcs_ids[parent_region_id] = []
            parent_id_to_dcs_ids[parent_region_id].append(dcs_id)

        for parent_id, hum_ids in parent_id_to_hum_ids.items():
            hum_ids = set(sorted(hum_ids))
            dcs_ids = parent_id_to_dcs_ids.get(parent_id, [])
            dcs_ids = set(sorted(dcs_ids))
            if len(hum_ids) != len(dcs_ids):
                continue
            print("\tPARENT ", parent_id)
            for hum_id in hum_ids:
                hum_name = region_id_to_name_hum[hum_id]
                print("\t\t- HUM ", hum_id, hum_name)
            for dcs_id in dcs_ids:
                dcs_name = region_id_to_name_dcs[dcs_id]
                print("\t\t- DCS ", dcs_id, dcs_name)

            for hum_id, dcs_id in zip(hum_ids, dcs_ids):
                hum_name = region_id_to_name_hum[hum_id]
                dcs_name = region_id_to_name_dcs[dcs_id]
                match_score = fuzz.ratio(dcs_name, str(hum_name))
                n_match_2 += 1
                lines.append(
                    "    "
                    + f'"{hum_id}": "{dcs_id}",'
                    + f"  # {n_match_1 + n_match_2:03d}."
                    + f" {hum_name} -> {dcs_name} ({match_score})"
                )

    if dcs_minus_hum == set() and hum_minus_dcs == set():
        print("✅ IDs MATCH")

        n_mismatch = 0
        for region_id in dcs_region_ids:
            dcs_name = region_id_to_name_dcs[region_id]
            hum_name = region_id_to_name_hum[region_id]

            match_score = fuzz.ratio(dcs_name, hum_name)

            if match_score < 90:
                print(
                    "\t❌ NAME MISMATCH",
                    region_id,
                    dcs_name,
                    hum_name,
                    match_score,
                )
                n_mismatch += 1

        if n_mismatch == 0:
            print("✅ NAMES MATCH")
        else:
            print(f"❌ {n_mismatch} NAME MISMATCHES")

    print(" ")
    lines.extend(
        [
            "}",
            "",
        ]
    )
    lines_file = File(os.path.join("workflows", f"{var_name}.DRAFT.py"))
    lines_file.write("\n".join(lines))
    print(f"Wrote {lines_file}")


if __name__ == "__main__":
    for dcs_region_label, hum_admin_level in [
        # ("province", 1),
        # ("district", 2),
        # ("dsd", 3),
        ("gnd", 4),
    ]:
        compare(dcs_region_label, hum_admin_level)
