import os
from functools import cache

from fuzzywuzzy import fuzz
from utils import File, JSONFile, Log, TSVFile

from lk_admin_regions.corrections.ID_CORRECTION_MAP_dsd import \
    ID_CORRECTION_MAP_dsd
from lk_admin_regions.corrections.ID_CORRECTION_MAP_gnd import \
    ID_CORRECTION_MAP_gnd
from lk_admin_regions.ground_truth.dcs.GNDListFinalXLSX import GNDListFinalXLSX
from lk_admin_regions.ground_truth.humdata.LKAAdminBoundariesXLSX import \
    LKAAdminBoundariesXLSX

log = Log("CombineDCSAndHumData")

ID_CORRECTION_MAP = ID_CORRECTION_MAP_dsd | ID_CORRECTION_MAP_gnd
NAME_MATCH_THRESHOLD = 0.75


class CombineDCSAndHumData:
    @staticmethod
    def correct(d_list, dcs_region_key, hum_region_key):
        corrected_d_list = []
        for d in d_list:
            region_id = "LK-" + d[hum_region_key][2:]
            for before, after in ID_CORRECTION_MAP.items():
                if before in region_id:
                    region_id = region_id.replace(before, after)
            d[dcs_region_key] = region_id
            corrected_d_list.append(d)
        return corrected_d_list

    @staticmethod
    def combine(dcs_region_label, hum_admin_level):
        var_name = f"ID_CORRECTION_MAP_{dcs_region_label}"
        lines = [
            "# ⚠️ Auto Generated by workflows/temp_analyze.py. REVIEW MANUALLY.",
            "# flake8: noqa: E501",
            "",
            "",
            f"{var_name} = {{",
        ]
        log.debug("-" * 32)
        log.debug(f"LEVEL {hum_admin_level} {dcs_region_label}")
        log.debug("-" * 32)

        dcs_region_id_key = f"{dcs_region_label}_id"
        dcs_region_name_key = f"{dcs_region_label}_name"
        hum_sheet_name = f"lka_admin{hum_admin_level}"
        hum_region_id_key = f"adm{hum_admin_level}_pcode"
        hum_region_name_key = f"adm{hum_admin_level}_name"
        data_dcs = GNDListFinalXLSX.get_data_list()
        data_hum = LKAAdminBoundariesXLSX.get_sheet_name_to_d_list()

        region_id_to_name_dcs = {
            d[dcs_region_id_key]: d[dcs_region_name_key] for d in data_dcs
        }

        data_hum_corrected = CombineDCSAndHumData.correct(
            data_hum[hum_sheet_name], dcs_region_id_key, hum_region_id_key
        )
        if len(data_hum_corrected) != len(data_hum[hum_sheet_name]):
            log.warning(
                "❌ HUM DUPLICATE IDS"
                + " "
                + len(data_hum_corrected)
                + " "
                + len(data_hum[hum_sheet_name]),
            )
        region_id_to_name_hum = {
            d[dcs_region_id_key]: str(d[hum_region_name_key])
            for d in data_hum_corrected
        }

        # IMPORTANT: For a DCS and HUM region to match,
        # they should match in both id (exactly) name (similar)

        dcs_minus_hum = set()
        n_match_0 = 0
        for dcs_id, dcs_name in region_id_to_name_dcs.items():
            hum_name = region_id_to_name_hum.get(dcs_id)
            if hum_name is None:
                dcs_minus_hum.add(dcs_id)
                continue

            match_score = fuzz.ratio(dcs_name, hum_name)
            if match_score < NAME_MATCH_THRESHOLD:
                dcs_minus_hum.add(dcs_id)

            n_match_0 += 1

        hum_minus_dcs = set()
        for hum_id, hum_name in region_id_to_name_hum.items():
            dcs_name = region_id_to_name_dcs.get(hum_id)
            if dcs_name is None:
                hum_minus_dcs.add(hum_id)
                continue
            match_score = fuzz.ratio(dcs_name, hum_name)
            if match_score < NAME_MATCH_THRESHOLD:
                hum_minus_dcs.add(hum_id)

        parent_id_to_hum_ids = {}
        for hum_id in hum_minus_dcs:
            parent_region_id = hum_id[:-3]
            if parent_region_id in ["LK-5221", "LK-5224"]:
                parent_region_id = "LK-5221/5224"

            if parent_region_id not in parent_id_to_hum_ids:
                parent_id_to_hum_ids[parent_region_id] = []
            parent_id_to_hum_ids[parent_region_id].append(hum_id)
        parent_id_to_dcs_ids = {}
        for dcs_id in dcs_minus_hum:
            parent_region_id = dcs_id[:-3]
            if parent_region_id in ["LK-5221", "LK-5224"]:
                parent_region_id = "LK-5221/5224"
            if parent_region_id not in parent_id_to_dcs_ids:
                parent_id_to_dcs_ids[parent_region_id] = []
            parent_id_to_dcs_ids[parent_region_id].append(dcs_id)

        all_parent_ids = set(parent_id_to_hum_ids.keys()) | set(
            parent_id_to_dcs_ids.keys()
        )
        all_parent_ids = sorted(all_parent_ids)
        for parent_id in all_parent_ids:
            hum_ids = parent_id_to_hum_ids.get(parent_id, [])
            dcs_ids = parent_id_to_dcs_ids.get(parent_id, [])
            log.debug(parent_id, len(dcs_ids), "DCS", len(hum_ids), "HUM")
            for dcs_id in dcs_ids:
                dcs_name = region_id_to_name_dcs[dcs_id]
                log.debug("\t- DCS " + dcs_id + " " + dcs_name)
            for hum_id in hum_ids:
                hum_name = region_id_to_name_hum[hum_id]
                log.debug("\t- HUM " + hum_id + " " + hum_name)
            log.debug("-" * 16)

        # ATTEMPT TO MATCH

        lines.extend(
            [
                "    #",
                "    # " + "=" * 64,
                "    # MATCH 1 - Similar Name",
                "    # " + "=" * 64,
                "    #",
            ]
        )
        # MATCH 1 = Check if there is a DCS region
        # a) without a HUM match,
        # b) with the same or similar name,
        # c) belonging to the same parent region.
        previous_parent_region_id = None
        n_match_1 = 0
        hum_minus_dcs = sorted(hum_minus_dcs)
        for hum_id in hum_minus_dcs:
            hum_name = region_id_to_name_hum[hum_id]
            match_list = []

            # 1.a
            for dcs_id in dcs_minus_hum:
                parent_region_id = dcs_id[:-3]
                # 1.b
                if parent_region_id not in hum_id:
                    continue
                # 1.c
                dcs_name = region_id_to_name_dcs[dcs_id]
                match_score = fuzz.ratio(dcs_name, hum_name)
                if match_score < 80:
                    continue
                match_list.append((dcs_id, dcs_name, match_score))

            match_list.sort(key=lambda x: x[2], reverse=True)
            n_matches = len(match_list)
            if n_matches:
                log.debug("\t" + hum_id + " " + hum_name)
                for dcs_id, dcs_name, match_score in match_list:
                    parent_region_id = dcs_id[:-3]
                    log.debug(
                        "\t\t- "
                        + dcs_id
                        + " "
                        + dcs_name
                        + " "
                        + str(match_score)
                    )
                    if parent_region_id != previous_parent_region_id:
                        lines.append("    " + "# --------")
                        lines.append("    " + f"# {parent_region_id}")
                        lines.append("    " + "# --------")
                        previous_parent_region_id = parent_region_id
                    n_match_1 += 1
                    lines.append(
                        "    "
                        + f'"{hum_id}": "{dcs_id}",'
                        + f"  # {n_match_1:03d}."
                        + f" {hum_name} -> {dcs_name} ({match_score})"
                    )
                    break

        # MATCH 2 - Check if some parent has exactly one DCS Gnd without match,
        # and exaclty one HUM Gnd without a match

        if not n_match_1:
            n_match_2 = 0
            lines.extend(
                [
                    "    #",
                    "    # " + "=" * 64,
                    "    # MATCH 2 - Parent with same num"
                    + " of unmatched HUM & DCS",
                    "    # " + "=" * 64,
                    "    #",
                ]
            )

            for parent_id, hum_ids in parent_id_to_hum_ids.items():
                hum_ids = sorted(hum_ids)
                dcs_ids = parent_id_to_dcs_ids.get(parent_id, [])
                dcs_ids = sorted(dcs_ids)
                if len(hum_ids) != len(dcs_ids):
                    continue
                log.debug("\tPARENT " + parent_id)
                for hum_id in hum_ids:
                    hum_name = region_id_to_name_hum[hum_id]
                    log.debug("\t\t- HUM " + hum_id + " " + hum_name)
                for dcs_id in dcs_ids:
                    dcs_name = region_id_to_name_dcs[dcs_id]
                    log.debug("\t\t- DCS " + dcs_id + " " + dcs_name)

                for hum_id, dcs_id in zip(hum_ids, dcs_ids):
                    hum_name = region_id_to_name_hum[hum_id]
                    dcs_name = region_id_to_name_dcs[dcs_id]
                    match_score = fuzz.ratio(dcs_name, hum_name)
                    n_match_2 += 1
                    lines.append(
                        "    "
                        + f'"{hum_id}": "{dcs_id}",'
                        + f"  # {n_match_1 + n_match_2:03d}."
                        + f" {hum_name} -> {dcs_name} ({match_score})"
                    )

        log.debug(" ")
        lines.extend(
            [
                "}",
                "",
            ]
        )
        lines_file = File(os.path.join("workflows", f"{var_name}.DRAFT.py"))
        lines_file.write("\n".join(lines))
        log.debug(f"Wrote {lines_file}")

        log.debug("-" * 32)
        log.debug("DCS ^ HUM = " + str(n_match_0))
        log.debug("DCS - HUM = " + str(len(dcs_minus_hum)))
        log.debug("HUM - DCS = " + str(len(hum_minus_dcs)))
        log.debug(
            "TOTAL MISMATCHES = "
            + str(len(dcs_minus_hum) + len(hum_minus_dcs))
        )

        region_id_to_data_dcs = {d[dcs_region_id_key]: d for d in data_dcs}
        region_id_to_data_hum = {
            d[dcs_region_id_key]: d for d in data_hum_corrected
        }

        valid_region_ids = sorted(
            set(region_id_to_name_dcs.keys())
            & set(region_id_to_name_hum.keys())
        )

        combined_d_list = []
        for region_id in valid_region_ids:
            data_dcs = region_id_to_data_dcs[region_id]
            data_hum = region_id_to_data_hum[region_id]
            d = {}
            for k, v in data_dcs.items():
                if k not in data_hum:
                    d["dcs_" + k] = v

            for k, v in data_hum.items():
                if k not in data_dcs:
                    d["hum_" + k] = v

            d["hum_valid_on"] = str(d["hum_valid_on"])
            gnd_code = int(d["dcs_gnd_code"])
            dsd_id = d["dcs_dsd_id"]
            gnd_id = f"{dsd_id}{gnd_code:03d}"
            d["dcs_gnd_id"] = gnd_id

            combined_d_list.append(d)
        log.debug(combined_d_list[0])
        tsv_file = TSVFile(
            os.path.join("data_temp", f"combined_{dcs_region_label}.tsv")
        )
        tsv_file.write(combined_d_list)
        log.info(f"Wrote {tsv_file}")

        json_sample_file = JSONFile(
            os.path.join(
                "data_temp", f"combined_{dcs_region_label}.sample.json"
            )
        )
        json_sample_file.write(combined_d_list[:10])
        log.info(f"Wrote {json_sample_file}")

    @classmethod
    @cache
    def get_data_list(cls):
        return TSVFile(os.path.join("data_temp", "combined_gnd.tsv")).read()

    @classmethod
    @cache
    def get_hum_id_to_dcs_id_map(cls, ent_type_name):
        data_list = cls.get_data_list()
        id_len = {
            "province": 4,
            "district": 5,
            "dsd": 7,
            "gnd": 10,
        }[ent_type_name]
        idx = {
            d["hum_adm4_pcode"][: id_len - 1]: d["dcs_gnd_id"][:id_len]
            for d in data_list
        }
        return idx
