# ⚠️ Auto Generated by workflows/temp_analyze.py. REVIEW MANUALLY.
# flake8: noqa: E501


ID_CORRECTION_MAP_gnd = {
    #
    # ================================================================
    # MATCH 1 - Similar Name
    # ================================================================
    #
    # --------
    # LK-2206
    # --------
    "LK-2206300": "LK-2206125",  # 001. Kandalama -> Kandalama (100)
    # --------
    # LK-3127
    # --------
    "LK-3127245": "LK-3127180",  # 002. Pahala Keembiya -> Pahala Keembiya (100)
    "LK-3127250": "LK-3127175",  # 003. Warakapitikanda -> Warakapitikanda (100)
    "LK-3127255": "LK-3127215",  # 004. Adurathvila -> Adurathvila (100)
    "LK-3127260": "LK-3127225",  # 005. Walpita South -> Walpita Soth (96)
    "LK-3127265": "LK-3127210",  # 006. Balagoda -> Balagoda (100)
    "LK-3127270": "LK-3127195",  # 007. Ginimellagaha South -> Ginimellagaha South (100)
    "LK-3127275": "LK-3127200",  # 008. Pituwalgoda -> Pituwalgoda (100)
    "LK-3127280": "LK-3127205",  # 009. Thelikada Nagaraya -> Thelikada Nagaraya (100)
    "LK-3127285": "LK-3127235",  # 010. Horagampita Central -> Horagampita Central (100)
    "LK-3127290": "LK-3127230",  # 011. Gonapura -> Gonapura (100)
    "LK-3127295": "LK-3127240",  # 012. Horagampita -> Horagampita (100)
    # --------
    # LK-3128
    # --------
    "LK-3128115": "LK-3128005",  # 013. Weihena -> Weihena (100)
    "LK-3128125": "LK-3128015",  # 014. Polgahavila -> Polgahavila (100)
    "LK-3128130": "LK-3128010",  # 015. Indurupathvila -> Indurupathvila (100)
    "LK-3128205": "LK-3128035",  # 016. Kirindalahena -> Kirindalahena (100)
    "LK-3128210": "LK-3128030",  # 017. Pahala Lelwala -> Pahala Lelwala (100)
    "LK-3128215": "LK-3128025",  # 018. Ihala Lelwala -> Ihala Lelwala (100)
    "LK-3128220": "LK-3128020",  # 019. Kumbalamalahena -> Kumbalamalaheana (97)
    "LK-3128225": "LK-3128050",  # 020. Wanduramba -> Wanduramba (100)
    "LK-3128230": "LK-3128055",  # 021. Gulugahakanda -> Gulugahakanda (100)
    "LK-3128235": "LK-3128045",  # 022. Panvila -> Panvila (100)
    "LK-3128240": "LK-3128040",  # 023. Kokawala -> Kokawala (100)
    "LK-3128300": "LK-3128080",  # 024. Meda Keembiya -> Mada Keembiya (92)
    "LK-3128305": "LK-3128075",  # 025. Deiyandara -> Deiyandara (100)
    "LK-3128310": "LK-3128070",  # 026. Wanduramba South -> Wanduramba South (100)
    "LK-3128315": "LK-3128060",  # 027. Thalawa -> Thalawa (100)
    "LK-3128320": "LK-3128065",  # 028. Mabotuwana -> Mabotuwana (100)
    "LK-3128325": "LK-3128095",  # 029. Nattewela -> Nattewela (100)
    "LK-3128330": "LK-3128090",  # 030. Thiruwanaketiya -> Thiruwanaketiya (100)
    "LK-3128335": "LK-3128085",  # 031. Pitiharawa -> Pitiharawa (100)
    "LK-3128340": "LK-3128100",  # 032. Meda Keembiya East -> Meda Keembiya East (100)
    "LK-3128345": "LK-3128105",  # 033. Ihala Keembiya South -> Ihala Keembiya South (100)
    "LK-3128350": "LK-3128110",  # 034. Ihala Keembiya -> Ihala Keembiya (100)
    # --------
    # LK-3136
    # --------
    "LK-3136195": "LK-3136005",  # 035. Wellawatta -> Wellawatta (100)
    "LK-3136205": "LK-3136030",  # 036. Wavulagoda West -> Wawulagoda West (93)
    "LK-3136210": "LK-3136035",  # 037. Wavulagoda East -> Wawulagoda East (93)
    "LK-3136215": "LK-3136020",  # 038. Hikkaduwa West -> Hikkaduwa  West (97)
    "LK-3136220": "LK-3136010",  # 039. Nakanda -> Nakanda (100)
    "LK-3136225": "LK-3136015",  # 040. Hikkaduwa Central -> Hikkaduwa Central (100)
    "LK-3136230": "LK-3136040",  # 041. Nalagasdeniya -> Nalagasdeniya (100)
    "LK-3136235": "LK-3136045",  # 042. Millagoda -> Millagoda (100)
    "LK-3136240": "LK-3136055",  # 043. Pannamgoda -> Pannamgoda (100)
    "LK-3136245": "LK-3136050",  # 044. Wewala -> Wewala (100)
    "LK-3136250": "LK-3136060",  # 045. Narigama Wellabada -> Narigama Wellabada (100)
    "LK-3136255": "LK-3136065",  # 046. Narigama -> Narigama (100)
    "LK-3136260": "LK-3136070",  # 047. Kuda Wewala -> Kuda Wewala (100)
    "LK-3136265": "LK-3136075",  # 048. Delgahadoowa -> Delgahadoowa (100)
    "LK-3136270": "LK-3136080",  # 049. Katukoliha -> Katukoliha (100)
    "LK-3136275": "LK-3136085",  # 050. Thiranagama -> Thiranagama (100)
    "LK-3136285": "LK-3136095",  # 051. Patuwatha -> Patuwatha (100)
    "LK-3136290": "LK-3136100",  # 052. Gammaduwatta -> Gammaduwatta (100)
    "LK-3136295": "LK-3136105",  # 053. Hennathota -> Hennathota (100)
    "LK-3136300": "LK-3136110",  # 054. Pinkanda -> Pinkanda (100)
    "LK-3136305": "LK-3136115",  # 055. Handaudumulla -> Handaudumulla (100)
    "LK-3136340": "LK-3136120",  # 056. Dodandugoda -> Dodandugoda (100)
    "LK-3136345": "LK-3136125",  # 057. Modara Patuwatha -> Modara Patuwatha (100)
    "LK-3136350": "LK-3136130",  # 058. Dodandoowa -> Dodandoowa (100)
    "LK-3136355": "LK-3136135",  # 059. Uduhalpitiya -> Uduhalpitiya (100)
    # --------
    # LK-3137
    # --------
    "LK-3137310": "LK-3137005",  # 060. Thotavila -> Thotawila (89)
    "LK-3137315": "LK-3137010",  # 061. Mawadavila -> Mawadawila (90)
    "LK-3137320": "LK-3137015",  # 062. Panvila Pahalagoda -> Panwila Pahalagoda (94)
    "LK-3137330": "LK-3137020",  # 063. Imbula -> Imbula (100)
    "LK-3137335": "LK-3137025",  # 064. Katudampe -> Katudampe (100)
    "LK-3137360": "LK-3137030",  # 065. Karawegoda -> Karawegoda (100)
    "LK-3137365": "LK-3137035",  # 066. Devinigoda -> Devinigoda (100)
    "LK-3137370": "LK-3137040",  # 067. Bopagoda -> Bopagoda (100)
    "LK-3137375": "LK-3137045",  # 068. Kandegoda -> Kandegoda (100)
    "LK-3137380": "LK-3137050",  # 069. Ranapanadeniya -> Ranapanadeniya (100)
    "LK-3137385": "LK-3137120",  # 070. Mahahegoda -> Maha Hegoda (86)
    "LK-3137390": "LK-3137060",  # 071. Medawala -> Medawala (100)
    "LK-3137395": "LK-3137125",  # 072. Hegoda -> Hegoda (100)
    "LK-3137400": "LK-3137070",  # 073. Palanthriyagoda -> Palanthriyagoda (100)
    "LK-3137405": "LK-3137065",  # 074. Maliduwa -> Maliduwa (100)
    "LK-3137410": "LK-3137115",  # 075. Rathna Udagama -> Ratna Udagama (96)
    "LK-3137415": "LK-3137075",  # 076. Ganegoda -> Ganegoda (100)
    "LK-3137420": "LK-3137080",  # 077. Rathgama Hegoda -> Rathgama Hegoda (100)
    "LK-3137425": "LK-3137085",  # 078. Palliyapitiya -> Palliyapitiya (100)
    "LK-3137430": "LK-3137090",  # 079. Gammeddegoda -> Gammeddagoda (92)
    "LK-3137435": "LK-3137095",  # 080. Gammeddegoda East -> Gammeddegoda East (100)
    "LK-3137440": "LK-3137100",  # 081. Gammeddegoda-Rajgama -> Gammeddegoda-Rajgama (100)
    "LK-3137445": "LK-3137105",  # 082. Owakanda -> Owakanda (100)
    "LK-3137450": "LK-3137110",  # 083. Kapumulugoda -> Kapumulugoda (100)
    "LK-3137455": "LK-3137140",  # 084. Dolikanda -> Dolikanda (100)
    "LK-3137460": "LK-3137145",  # 085. Boossa -> Boosa (91)
    "LK-3137465": "LK-3137135",  # 086. Rupeewala -> Rupeewala (100)
    "LK-3137470": "LK-3137130",  # 087. Kedala -> Kedala (100)
    "LK-3137475": "LK-3137155",  # 088. Pitiwella South -> Pitiwella South (100)
    "LK-3137480": "LK-3137160",  # 089. Pitiwella North -> Pitiwella North (100)
    "LK-3137485": "LK-3137150",  # 090. Kadurupe -> Kadurupe (100)
    # --------
    # LK-9103
    # --------
    "LK-9103051": "LK-9103215",  # 091. Karandana South -> Karandana South (100)
    "LK-9103052": "LK-9103210",  # 092. Karandana West -> Karandana West (100)
    # --------
    # LK-9106
    # --------
    "LK-9106141": "LK-9106005",  # 093. Amuhenkanda -> Amuhenkanda (100)
    "LK-9106142": "LK-9106010",  # 094. Pathberiya West -> Pathberiya West (100)
    "LK-9106143": "LK-9106015",  # 095. Pathberiya -> Pathberiya (100)
    "LK-9106144": "LK-9106025",  # 096. Parakaduwa -> Parakaduwa (100)
    "LK-9106146": "LK-9106030",  # 097. Bodhimaluwa -> Bodhimaluwa (100)
    "LK-9106147": "LK-9106035",  # 098. Thalavitiya -> Thalavitiya (100)
    "LK-9106148": "LK-9106040",  # 099. Pohorabawa -> Pohorabawa (100)
    "LK-9106149": "LK-9106100",  # 100. Miyanadeniya -> Miyanadeniya (100)
    # --------
    # LK-9118
    # --------
    "LK-9118210": "LK-9118165",  # 101. Damahana -> Damahana (100)
    "LK-9118230": "LK-9118170",  # 102. Godakumbura -> Godakumbura (100)
    "LK-9118235": "LK-9118175",  # 103. Imbulamura -> Imbulamura (100)
    "LK-9118240": "LK-9118180",  # 104. Mahawalathenna -> Mahawalathenna (100)
    "LK-9118245": "LK-9118185",  # 105. Theladiriya -> Theladiriya (100)
    "LK-9118250": "LK-9118190",  # 106. Mawela -> Mawela (100)
    "LK-9118255": "LK-9118195",  # 107. Welage -> Welage (100)
    "LK-9118260": "LK-9118200",  # 108. Gawaranhena -> Gawaranhena (100)
    "LK-9118265": "LK-9118205",  # 109. Horaketiya -> Horaketiya (100)
    # --------
    # LK-9119
    # --------
    "LK-9119065": "LK-9119010",  # 110. Kalthota -> Kalthota (100)
    "LK-9119070": "LK-9119015",  # 111. Uggalkalthota Left Bank South -> Uggalkalthota Left Bank South (100)
    "LK-9119075": "LK-9119020",  # 112. Medabedda -> Medabedda (100)
    "LK-9119080": "LK-9119025",  # 113. Neluyaya -> Neluyaya (100)
    "LK-9119085": "LK-9119030",  # 114. Uggalkalthota Left Bank Left -> Uggalkalthota Left Bank Left (100)
    "LK-9119090": "LK-9119035",  # 115. Welipathayaya -> Welipathayaya (100)
    "LK-9119095": "LK-9119040",  # 116. Kuragala -> Kuragala (100)
    "LK-9119100": "LK-9119045",  # 117. Molamura -> Molamura (100)
    "LK-9119215": "LK-9119050",  # 118. Kongahamankada -> Kongahamankada (100)
    "LK-9119220": "LK-9119055",  # 119. Kalupedigama -> Kalupedigama (100)
    "LK-9119225": "LK-9119060",  # 120. Diyavinna -> Diyavinna (100)
    #
    # ================================================================
    # MATCH 2 - Parent with same num of unmatched HUM & DCS
    # ================================================================
    #
    "LK-3136200": "LK-3136025",  # 001. Hikkaduwa Nagarikaya -> Hikkaduwa Town (59)
    "LK-3136280": "LK-3136090",  # 002. Thiranagama Wellabada -> Wellabada Thiranagama (52)
    "LK-8215135": "LK-8215105",  # 003. nan -> Horombuwa (17)
    "LK-3137325": "LK-3137055",  # 004. Rejjipura -> Reggipura (78)
    "LK-2218265": "LK-2218120",  # 005. nan -> Kirigalpotta (13)
    "LK-8218210": "LK-8218090",  # 006. nan -> Pussellawa (15)
    "LK-2215285": "LK-2215150",  # 007. nan -> Aluthwatta (15)
    "LK-2221150": "LK-2221090",  # 008. nan -> Aluthwela (17)
    #
    # ================================================================
    # MATCH 2 - Parent with same num of unmatched HUM & DCS
    # ‼️ HACK for Kalmunai North
    # ================================================================
    #
    "LK-5224150": "LK-5221005",  # 001. nan -> Periyaneelavanai  01B (17)
    "LK-5224155": "LK-5221010",  # 002. nan -> Periyaneelavanai  01A (17)
    "LK-5224160": "LK-5221015",  # 003. nan -> Periyaneelavanai  01 (17)
    "LK-5224165": "LK-5221020",  # 004. nan -> Periyaneelavanai  02 (17)
    "LK-5224170": "LK-5221025",  # 005. nan -> Chenaikudiyiruppu 01A (17)
    "LK-5224175": "LK-5221030",  # 006. nan -> Pandiruppu 01 (25)
    "LK-5224180": "LK-5221035",  # 007. nan -> Pandiruppu 01B (24)
    "LK-5224185": "LK-5221040",  # 008. nan -> Pandiruppu 01C (24)
    "LK-5224190": "LK-5221045",  # 009. nan -> Pandiruppu 01A (24)
    "LK-5224195": "LK-5221050",  # 010. nan -> Pandiruppu 02_x000D_ (17)
    "LK-5224200": "LK-5221055",  # 011. nan -> Pandiruppu 02B (24)
    "LK-5224205": "LK-5221060",  # 012. nan -> Pandiruppu 02C (24)
    "LK-5224210": "LK-5221065",  # 013. nan -> Pandiruppu 02A (24)
    "LK-5224215": "LK-5221070",  # 014. nan -> Kalmunai  01D (25)
    "LK-5224230": "LK-5221075",  # 015. nan -> Kalmunai  01B (25)
    "LK-5224235": "LK-5221080",  # 016. nan -> Kalmunai  01A (25)
    "LK-5224240": "LK-5221085",  # 017. nan -> Kalmunai  01 (27)
    "LK-5224245": "LK-5221090",  # 018. nan -> Natpiddimunai (T.P ) 03 (15)
    "LK-5224250": "LK-5221095",  # 019. nan -> Natpiddimunai (T.P ) 02 (15)
    "LK-5224255": "LK-5221100",  # 020. nan -> Natpiddimunai (T.P ) 01 (15)
    "LK-5224260": "LK-5221105",  # 021. nan -> Chenaikudiyiruppu 01B (17)
    "LK-5224265": "LK-5221110",  # 022. nan -> Chenaikudiyiruppu 01 (17)
    "LK-5224270": "LK-5221115",  # 023. nan -> Kalmunai  01C (25)
    "LK-5224275": "LK-5221120",  # 024. nan -> Kalmunai  01E (25)
    "LK-5224280": "LK-5221125",  # 025. nan -> Kalmunai  02B (25)
    "LK-5224285": "LK-5221130",  # 026. nan -> Kalmunai  02A (25)
    "LK-5224290": "LK-5221135",  # 027. nan -> Kalmunai  02 (27)
    "LK-5224295": "LK-5221140",  # 028. nan -> Kalmunai  03 (27)
    "LK-5224300": "LK-5221145",  # 029. nan -> Kalmunai  03A (25)
}
